apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: user
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: user
  chart:
    repository: https://payticon-charts.devticon.com
    name: user
    version: 1.0.7-test-3
    values:
      - adminPasssword: Test1234