apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: user
  chart:
    repository: https://payticon-charts.devticon.com
    name: partner
    version: 1.0.2
